variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
- export PATH="/wbin/opt/gcc-arm-none-eabi-6-2017-q2-update/bin:$PATH"

stages:
- build

build:
  stage: build
  script:
    - make clean
    - make all
  tags:
    - armgcc
  artifacts:
    expire_in:
      4 weeks
    paths:
      - Hexfile/TS100_NG.hex
