language: c

addons: 
  apt: 
    packages: 
    - gcc-arm-none-eabi 
    - binutils-arm-none-eabi 
    - libnewlib-arm-none-eabi 
    - libstdc++-arm-none-eabi-newlib
    - srecord 

script: 
- make 
